app:
    message: This profile is a test configuration

# datasource
spring: 
    datasource:
        url: jdbc:mariadb://localhost:3307/bookstore_test
        username: root
        password: root

    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate.ddl-auto: update
        properties:
            hibernate: 
                show_sql: true