app:
    message: This profile is a development configuration

# datasource
spring: 
    datasource:
        url: jdbc:mariadb://localhost:3306/bookstore
        username: root
        password: root

    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate.ddl-auto: update
        properties:
            hibernate: 
                show_sql: true

api:
    security:
        token:
            secret: ${SECRET_KEY_JWT:"123456"}